version: '3'

services:
  api: &api
    build:
      context: .
      dockerfile: compose/prod/Dockerfile
    image: yavolonter-prod-api
    container_name: yavolonter-prod-api
    command: bash -c "
        cd src/
        && poetry run ./manage.py migrate
        && poetry run gunicorn —Åore.wsgi:application"
    volumes:
      - ./src/:/app/src/
    ports:
      - 8000:8000
    env_file:
      - compose/prod/.env

  celeryworker:
    <<: *api
    image: yavolonter-prod-celeryworker
    container_name: yavolonter-prod-celeryworker
    command: poetry run celery -A core.celery worker -l info
    ports: []
