version: '3'

services:
  django:
    build: './'
    command: poetry run ./manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - env_conf/.dev.env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=database

volumes:
  pg-data:
