version: '3'

services:
  api: &api
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    image: yavolonter-prod-api
    container_name: yavolonter-prod-api
    command: bash -c "
        poetry run ./manage.py migrate
        && poetry run gunicorn —Åore.wsgi:application -c config/gunicorn.conf.py --bind 0.0.0.0:8000"
    volumes:
      - ./src/:/app/src/
    ports:
      - 8000:8000
    env_file:
      - compose/local/.env
      - compose/local/.pg.env
    depends_on:
      - pg

  celeryworker:
    <<: *api
    image: yavolonter-prod-celeryworker
    container_name: yavolonter-prod-celeryworker
    command: poetry run celery -A core.celery worker -l info
    depends_on:
      - redis
      - pg
    ports: []
